version: '3.5'

services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-app
    restart: 'always'
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - '8001:80'

  mysql-db:
    image: mysql:5.7
    container_name: mysql
    restart: 'always'
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=allen_group
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: 'always'
    links:
      - mysql-db
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
    ports:
      - '8002:80'
